### PR TITLE
feat(ratelimit): add ratelimit/bbr algorithm

### PR DESCRIPTION
**Pull request by kagaya85**
Migrate bbr algorithm to kratos v2

resolve go-kratos/kratos#889

please hold this pr until go-kratos/kratos#1271 merged

Done:
- [x] remove `allowOptions` in `Limiter` interface for better decoupling
- [x] remove `doneInfo` for none use
- [x] remove limiter group because it may be replaced by selector
- [x] refactor `bbr` config to functional options
- [x] rename some variable to improved code readability, like `windowSize`, `bucketNum`, etc.
- [x] refactor some function, like `apply` in policy.go (original function name is `add`)
- [x] add and refactor some unit test cases
- [x] change bbr/cpuproc ticker interval from 250ms to 500ms
- [x] extract cpu and rolling window module

### CODE REVIEW

**Comment by Windfarer** [comment]
It is not recommended to depend on the kratos interface, so that this package can be used independently.

**Comment by kagaya85** [comment]
> It is not recommended to depend on the kratos interface, so that this package can be used independently.

ok, I removed these dependencies

**Comment by longXboy** [comment]
ratelimit/bbr/cpu/cgroup.go 
获取cpu使用率的具体实现应该抽到外层吧？这样别的地方也能复用到

**Comment by kagaya85** [comment]
> ratelimit/bbr/cpu/cgroup.go
> 获取cpu使用率的具体实现应该抽到外层吧？这样别的地方也能复用到

`cpu`和`rolling_window`的包是放在`internal`下还是`pkg`下比较好？

**Comment by kagaya85** [comment]
@longXboy done，现在cpu和window都拆了出来放到pkg下可以单独引用
ScreenShot_2021-08-07_at_15 07 17@2x

**Comment by longXboy** [comment]
> @longXboy done，现在cpu和window都拆了出来放到pkg下可以单独引用
> ScreenShot_2021-08-07_at_15 07 17@2x

可以的

**Review by longXboy — APPROVED** [review]

**Comment by longXboy** [comment]
LGTM

**Pull request merged**
